export const customThemes = {
  mono: {
    name: "Mono",
    background: {
      from: "#333",
      to: "#181818",
    },
    syntax: {
      light: {
        "--syntax-background": "rgba(0,0,100,0.75)",
        "--syntax-text": "#111111",
        "--syntax-variable": "#111111",
        "--syntax-variable-2": "#111111",
        "--syntax-variable-3": "#111111",
        "--syntax-attribute": "#666666",
        "--syntax-definition": "#111111",
        "--syntax-keyword": "#666666",
        "--syntax-operator": "#666666",
        "--syntax-property": "#666666",
        "--syntax-number": "#111111",
        "--syntax-string": "#666666",
        "--syntax-comment": "#999999",
        "--syntax-meta": "#666666",
        "--syntax-tag": "#666666",
      },
      dark: {
        "--syntax-background": "rgba(0,0,0,0.75)",
        "--syntax-text": "#ffffff",
        "--syntax-variable": "#ffffff",
        "--syntax-variable-2": "#ffffff",
        "--syntax-variable-3": "#ffffff",
        "--syntax-attribute": "#a7a7a7",
        "--syntax-definition": "#ffffff",
        "--syntax-keyword": "#a7a7a7",
        "--syntax-operator": "#a7a7a7",
        "--syntax-property": "#a7a7a7",
        "--syntax-number": "#ffffff",
        "--syntax-string": "#a7a7a7",
        "--syntax-comment": "#666666",
        "--syntax-meta": "#a7a7a7",
        "--syntax-tag": "#a7a7a7",
      },
    },
  },
  breeze: {
    name: "Breeze",
    background: {
      from: "rgba(207,47,152,1)",
      to: "rgba(106,61,236,1)",
    },
    syntax: {
      light: {
        "--syntax-background": "rgba(0,0,100,0.75)",
        "--syntax-text": "#434447",
        "--syntax-variable": "#F8518D",
        "--syntax-variable-2": "#BF3F6D",
        "--syntax-variable-3": "#238600",
        "--syntax-attribute": "#C44170",
        "--syntax-definition": "#C44170",
        "--syntax-keyword": "#496EB8",
        "--syntax-operator": "#496EB8",
        "--syntax-property": "#0B7880",
        "--syntax-number": "#24805E",
        "--syntax-string": "#886594",
        "--syntax-comment": "#8C828B",
        "--syntax-meta": "#625B6B",
        "--syntax-tag": "#4B71BD",
      },
      dark: {
        "--syntax-background": "rgba(0,0,0,0.75)",
        "--syntax-text": "#FFFFFF",
        "--syntax-variable": "#F8518D",
        "--syntax-variable-2": "#FFFFFF",
        "--syntax-variable-3": "#9AEC7D",
        "--syntax-attribute": "#F8518D",
        "--syntax-definition": "#F8518D",
        "--syntax-keyword": "#6599FF",
        "--syntax-operator": "#6599FF",
        "--syntax-property": "#49E8F2",
        "--syntax-number": "#55E7B2",
        "--syntax-string": "#E9AEFE",
        "--syntax-comment": "#8A757D",
        "--syntax-meta": "#ECFEEF",
        "--syntax-tag": "#6599FF",
      },
    },
  },
  candy: {
    name: "Candy",
    background: {
      from: "rgba(165,142,251,1)",
      to: "rgba(233,191,248,1)",
    },
    syntax: {
      light: {
        "--syntax-background": "rgba(0,0,100,0.75)",
        "--syntax-text": "#434447",
        "--syntax-variable": "#009033",
        "--syntax-variable-2": "#63676A",
        "--syntax-variable-3": "#D35A35",
        "--syntax-attribute": "#009033",
        "--syntax-definition": "#009033",
        "--syntax-keyword": "#DC155E",
        "--syntax-operator": "#d15a8b",
        "--syntax-property": "#2286A6",
        "--syntax-number": "#676DFF",
        "--syntax-string": "#B2762E",
        "--syntax-comment": "#8D949B",
        "--syntax-meta": "#6A6367",
        "--syntax-tag": "#d15a8b",
      },
      dark: {
        "--syntax-background": "rgba(0,0,0,0.75)",
        "--syntax-text": "#FFFFFF",
        "--syntax-variable": "#73DFA5",
        "--syntax-variable-2": "#FFFFFF",
        "--syntax-variable-3": "#E08569",
        "--syntax-attribute": "#73DFA5",
        "--syntax-definition": "#73DFA5",
        "--syntax-keyword": "#FF659C",
        "--syntax-operator": "#FF659C",
        "--syntax-property": "#1AC8FF",
        "--syntax-number": "#7A7FFD",
        "--syntax-string": "#DFD473",
        "--syntax-comment": "#807796",
        "--syntax-meta": "#F1ECFE",
        "--syntax-tag": "#FF659C",
      },
    },
  },
  crimson: {
    name: "Crimson",
    background: {
      from: "rgba(255,99,99,1)",
      to: "rgba(115,52,52,1)",
    },
    syntax: {
      light: {
        "--syntax-background": "rgba(0,0,100,0.75)",
        "--syntax-text": "#685B5B",
        "--syntax-variable": "#9E7070",
        "--syntax-variable-2": "#B22D2D",
        "--syntax-variable-3": "#D46184",
        "--syntax-attribute": "#9E7070",
        "--syntax-definition": "#9E7070",
        "--syntax-keyword": "#BE3B3B",
        "--syntax-operator": "#BE3B3B",
        "--syntax-property": "#D15510",
        "--syntax-number": "#C94F0A",
        "--syntax-string": "#836250",
        "--syntax-comment": "#978A8A",
        "--syntax-meta": "#8B5F5C",
        "--syntax-tag": "#BE3B3B",
      },
      dark: {
        "--syntax-background": "rgba(0,0,0,0.75)",
        "--syntax-text": "#FEFDFD",
        "--syntax-variable": "#C88E8E",
        "--syntax-variable-2": "#FFE4E4",
        "--syntax-variable-3": "#E97598",
        "--syntax-attribute": "#C88E8E",
        "--syntax-definition": "#C88E8E",
        "--syntax-keyword": "#EB6F6F",
        "--syntax-operator": "#EB6F6F",
        "--syntax-property": "#D15510",
        "--syntax-number": "#FDA97A",
        "--syntax-string": "#EBB99D",
        "--syntax-comment": "#895E60",
        "--syntax-meta": "#FFE4E4",
        "--syntax-tag": "#EB6F6F",
      },
    },
  },
  falcon: {
    name: "Falcon",
    background: {
      from: "rgba(189,227,236,1)",
      to: "rgba(54,54,84,1)",
    },
    syntax: {
      light: {
        "--syntax-background": "rgba(0,0,100,0.75)",
        "--syntax-text": "#464C65",
        "--syntax-variable": "#6A7C9F",
        "--syntax-variable-2": "#354BA7",
        "--syntax-variable-3": "#46615D",
        "--syntax-attribute": "#6A7C9F",
        "--syntax-definition": "#6A7C9F",
        "--syntax-keyword": "#5C827D",
        "--syntax-operator": "#5C827D",
        "--syntax-property": "#839AA7",
        "--syntax-number": "#AE6A65",
        "--syntax-string": "#506483",
        "--syntax-comment": "#9DA4AD",
        "--syntax-meta": "#425295",
        "--syntax-tag": "#5C827D",
      },
      dark: {
        "--syntax-background": "rgba(0,0,0,0.75)",
        "--syntax-text": "#FFFFFF",
        "--syntax-variable": "#6D88BB",
        "--syntax-variable-2": "#E4F2FF",
        "--syntax-variable-3": "#789083",
        "--syntax-attribute": "#6D88BB",
        "--syntax-definition": "#6D88BB",
        "--syntax-keyword": "#9AB6B2",
        "--syntax-operator": "#9AB6B2",
        "--syntax-property": "#799DB1",
        "--syntax-number": "#BD9C9C",
        "--syntax-string": "#6A8697",
        "--syntax-comment": "#6D7E88",
        "--syntax-meta": "#E4F2FF",
        "--syntax-tag": "#9AB6B2",
      },
    },
  },
  meadow: {
    name: "Meadow",
    background: {
      from: "rgba(89,212,153,1)",
      to: "rgba(160,135,45,1)",
    },
    syntax: {
      light: {
        "--syntax-background": "rgba(0,0,100,0.75)",
        "--syntax-text": "#54594D",
        "--syntax-variable": "#798B52",
        "--syntax-variable-2": "#6E967E",
        "--syntax-variable-3": "#99A607",
        "--syntax-attribute": "#798B52",
        "--syntax-definition": "#798B52",
        "--syntax-keyword": "#049649",
        "--syntax-operator": "#049649",
        "--syntax-property": "#B6781B",
        "--syntax-number": "#2C8801",
        "--syntax-string": "#837E50",
        "--syntax-comment": "#72806E",
        "--syntax-meta": "#5C8B6F",
        "--syntax-tag": "#049649",
      },
      dark: {
        "--syntax-background": "rgba(0,0,0,0.75)",
        "--syntax-text": "#FFFFFF",
        "--syntax-variable": "#B3D767",
        "--syntax-variable-2": "#E5FFE4",
        "--syntax-variable-3": "#2EFFB4",
        "--syntax-attribute": "#B3D767",
        "--syntax-definition": "#B3D767",
        "--syntax-keyword": "#6DD79F",
        "--syntax-operator": "#6DD79F",
        "--syntax-property": "#E4B165",
        "--syntax-number": "#46B114",
        "--syntax-string": "#E9EB9D",
        "--syntax-comment": "#708B6C",
        "--syntax-meta": "#E5FFE4",
        "--syntax-tag": "#6DD79F",
      },
    },
  },
  midnight: {
    name: "Midnight",
    background: {
      from: "rgba(76,200,200,1)",
      to: "rgba(32,32,51,1)",
    },
    syntax: {
      light: {
        "--syntax-background": "rgba(0,0,100,0.75)",
        "--syntax-text": "#434447",
        "--syntax-variable": "#2F788F",
        "--syntax-variable-2": "#63676A",
        "--syntax-variable-3": "#5D70B5",
        "--syntax-attribute": "#2F788F",
        "--syntax-definition": "#2F788F",
        "--syntax-keyword": "#587678",
        "--syntax-operator": "#587678",
        "--syntax-property": "#766599",
        "--syntax-number": "#2D8264",
        "--syntax-string": "#5F758F",
        "--syntax-comment": "#78808C",
        "--syntax-meta": "#5B636B",
        "--syntax-tag": "#5A797A",
      },
      dark: {
        "--syntax-background": "rgba(0,0,0,0.75)",
        "--syntax-text": "#FFFFFF",
        "--syntax-variable": "#51D0F8",
        "--syntax-variable-2": "#FFFFFF",
        "--syntax-variable-3": "#626B8B",
        "--syntax-attribute": "#51D0F8",
        "--syntax-definition": "#51D0F8",
        "--syntax-keyword": "#7DA9AB",
        "--syntax-operator": "#7DA9AB",
        "--syntax-property": "#9681C2",
        "--syntax-number": "#75D2B1",
        "--syntax-string": "#6D86A4",
        "--syntax-comment": "#4A4C56",
        "--syntax-meta": "#F2F7F7",
        "--syntax-tag": "#7DA9AB",
      },
    },
  },
  raindrop: {
    name: "Raindrop",
    background: {
      from: "rgba(142,199,251,1)",
      to: "rgba(28,85,170,1)",
    },
    syntax: {
      light: {
        "--syntax-background": "rgba(0,0,100,0.75)",
        "--syntax-text": "#687077",
        "--syntax-variable": "#4F9488",
        "--syntax-variable-2": "#687077",
        "--syntax-variable-3": "#2E81FF",
        "--syntax-attribute": "#4F9488",
        "--syntax-definition": "#4F9488",
        "--syntax-keyword": "#008DAC",
        "--syntax-operator": "#008DAC",
        "--syntax-property": "#007BA1",
        "--syntax-number": "#7459E1",
        "--syntax-string": "#507683",
        "--syntax-comment": "#6E7780",
        "--syntax-meta": "#5C838B",
        "--syntax-tag": "#008DAC",
      },
      dark: {
        "--syntax-background": "rgba(0,0,0,0.75)",
        "--syntax-text": "#E4F2FF",
        "--syntax-variable": "#1AD6B5",
        "--syntax-variable-2": "#E4F2FF",
        "--syntax-variable-3": "#2E81FF",
        "--syntax-attribute": "#1AD6B5",
        "--syntax-definition": "#1AD6B5",
        "--syntax-keyword": "#2ED9FF",
        "--syntax-operator": "#2ED9FF",
        "--syntax-property": "#008BB7",
        "--syntax-number": "#9984EE",
        "--syntax-string": "#9DD8EB",
        "--syntax-comment": "#6C808B",
        "--syntax-meta": "#ECFBFE",
        "--syntax-tag": "#2ED9FF",
      },
    },
  },
  sunset: {
    name: "Sunset",
    background: {
      from: "rgba(255,207,115,1)",
      to: "rgba(255,122,47,1)",
    },
    syntax: {
      light: {
        "--syntax-background": "rgba(0,0,100,0.75)",
        "--syntax-text": "#737568",
        "--syntax-variable": "#807410",
        "--syntax-variable-2": "#717365",
        "--syntax-variable-3": "#8C6A29",
        "--syntax-attribute": "#807410",
        "--syntax-definition": "#807410",
        "--syntax-keyword": "#A1642C",
        "--syntax-operator": "#A1642C",
        "--syntax-property": "#AD5A78",
        "--syntax-number": "#856F00",
        "--syntax-string": "#8C703C",
        "--syntax-comment": "#7A7055",
        "--syntax-meta": "#6B625B",
        "--syntax-tag": "#A1642C",
      },
      dark: {
        "--syntax-background": "rgba(0,0,0,0.75)",
        "--syntax-text": "#FFFFFF",
        "--syntax-variable": "#E2D66B",
        "--syntax-variable-2": "#FFFFFF",
        "--syntax-variable-3": "#E7B555",
        "--syntax-attribute": "#E2D66B",
        "--syntax-definition": "#E2D66B",
        "--syntax-keyword": "#FFAF65",
        "--syntax-operator": "#FFAF65",
        "--syntax-property": "#E978A1",
        "--syntax-number": "#E7CF55",
        "--syntax-string": "#F9D38C",
        "--syntax-comment": "#878572",
        "--syntax-meta": "#FFFDED",
        "--syntax-tag": "#FFAF65",
      },
    },
  },
};
